# Generated by Django 3.2.7 on 2021-12-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opioidID', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={},
        ),
    ]
