# Generated by Django 3.2.7 on 2021-12-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opioidID', '0002_alter_credential_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'managed': False},
        ),
    ]
