# Generated by Django 3.2.7 on 2021-12-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opioidID', '0003_alter_credential_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriberCredential',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prescriber_credential',
                'managed': False,
            },
        ),
    ]
