# Generated by Django 3.2.7 on 2021-12-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opioidID', '0004_prescribercredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescriberCredential',
        ),
        migrations.AlterModelTable(
            name='credential',
            table='prescriber_credential',
        ),
    ]
